language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

sudo: required
dist: trusty
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.9
  - sudo apt-get install -y build-essential libtool automake autotools-dev autoconf pkg-config libssl-dev libcrypto++-dev libevent-dev git libboost-all-dev 
  - sudo add-apt-repository -y ppa:bitcoin/bitcoin
  - sudo apt-get update -y && sudo apt-get install -y libdb4.8-dev libdb4.8++-dev libzmq3-dev
  - sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libcrypto++-dev libqrencode-dev
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - ./ci/build_depends.sh
  - ./autogen.sh && ./configure --with-gui && make
